# database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/oems
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update


# server port
server.port = 7000

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html

# value
jwt.token.secret=dANm==F+hL/iKGnHaB5RUxhaq=SK4ZtVqdnnuBUxit=NEycSHZc
jwt.token.expiration=86400000

