# database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/oems
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
sprint.datasource.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# server port
server.port = 7000

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html

# value
jwt.expiration-ms=43200000

jwt.secret=dANm==F+hL/iKGnHaB5RUxhaq=SK4ZtVqdnnuBUxit=NEycSHZc
spring.main.allow-circular-references=true

app.upload.profile-dir=./uploads/profile


# DeepSeek API Settings
spring.ai.openai.api-key=sk-78fd8e0b046c4764bff89e6767bff466
spring.ai.openai.base-url=https://api.deepseek.com
# Disable default model to ensure we use our programmatic ones
spring.ai.openai.chat.options.model=deepseek-chat


springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha